### ISSUE TITLE
docs.rs build is broken

### ISSUE THREAD

**Issue by luser** [getsentry/symbolic#128]
I went to look at the docs.rs page for symbolic and it gave an error message. Poking around a bit I found that [this page](https://docs.rs/crate/symbolic/5.7.8) exists which points to [a build log](https://docs.rs/crate/symbolic/5.7.8/builds/136317) where the crate is failing to build in docs.rs' system. The errors from the log are failing to compile some Breakpad sources:
```
running: "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-o" "/home/cratesfyi/cratesfyi/debug/build/symbolic-minidump-1530eb319d313ef2/out/third_party/breakpad/src/third_party/libdisasm/ia32_implicit.o" "-c" "third_party/breakpad/src/third_party/libdisasm/ia32_implicit.c"
running: "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-o" "/home/cratesfyi/cratesfyi/debug/build/symbolic-minidump-1530eb319d313ef2/out/third_party/breakpad/src/third_party/libdisasm/ia32_settings.o" "-c" "third_party/breakpad/src/third_party/libdisasm/ia32_settings.c"
cargo:warning=cc: error: third_party/breakpad/src/third_party/libdisasm/ia32_implicit.c: No such file or directory
cargo:warning=cc: fatal error: no input files
cargo:warning=compilation terminated.
exit code: 1
```

I can reproduce this locally creating an empty crate with a dependency on `symbolic` with the `minidump` feature enabled:
```toml
[dependencies]
symbolic = { version = "5.7.8", features = ["minidump"] }
```

It looks like the published `symbolic-minidump` crate doesn't contain the Breakpad sources at all?

```
$ tar tzf /home/luser/.cargo/registry/cache/github.com-1ecc6299db9ec823/symbolic-minidump-5.7.8.crate
symbolic-minidump-5.7.8/Cargo.toml.orig
symbolic-minidump-5.7.8/Cargo.toml
symbolic-minidump-5.7.8/build.rs
symbolic-minidump-5.7.8/cpp/c_mapping.h
symbolic-minidump-5.7.8/cpp/c_string.cpp
symbolic-minidump-5.7.8/cpp/c_string.h
symbolic-minidump-5.7.8/cpp/data_definitions.h
symbolic-minidump-5.7.8/cpp/data_structures.cpp
symbolic-minidump-5.7.8/cpp/data_structures.h
symbolic-minidump-5.7.8/cpp/memstream.h
symbolic-minidump-5.7.8/cpp/mmap_symbol_supplier.cpp
symbolic-minidump-5.7.8/cpp/mmap_symbol_supplier.h
symbolic-minidump-5.7.8/cpp/processor.cpp
symbolic-minidump-5.7.8/cpp/processor.h
symbolic-minidump-5.7.8/src/cfi.rs
symbolic-minidump-5.7.8/src/lib.rs
symbolic-minidump-5.7.8/src/processor.rs
symbolic-minidump-5.7.8/src/registers.rs
symbolic-minidump-5.7.8/src/utils.rs
symbolic-minidump-5.7.8/tests/snapshots/cfi_elf.txt
symbolic-minidump-5.7.8/tests/snapshots/cfi_macho.txt
symbolic-minidump-5.7.8/tests/snapshots/cfi_sym_linux.txt
symbolic-minidump-5.7.8/tests/snapshots/cfi_sym_macos.txt
symbolic-minidump-5.7.8/tests/snapshots/cfi_sym_windows.txt
symbolic-minidump-5.7.8/tests/snapshots/process_state_linux.txt
symbolic-minidump-5.7.8/tests/snapshots/process_state_macos.txt
symbolic-minidump-5.7.8/tests/snapshots/process_state_windows.txt
symbolic-minidump-5.7.8/tests/snapshots/referenced_modules_linux.txt
symbolic-minidump-5.7.8/tests/snapshots/referenced_modules_macos.txt
symbolic-minidump-5.7.8/tests/snapshots/referenced_modules_windows.txt
symbolic-minidump-5.7.8/tests/test_cfi.rs
symbolic-minidump-5.7.8/tests/test_processor.rs
```

**Comment by jan-auer** [comment]
@luser Yes, the breakpad sources are currently in a submodule and we neglegted to make this work. This definitely needs to change, and I guess we could follow a similar pattern as [curl-sys](https://github.com/alexcrichton/curl-rust/blob/ce920a4f17eea119255ee8305ae7c29f615e778e/curl-sys/build.rs#L44-L47) to download the symbols as needed.

There's a major rewrite of symbolic under way in #127, I'll try to fit this in there. The most recent versions of symbolic also haven't been released on crates.io since we had to rely on a bunch of git dependencies. The next major bump will also land on crates.io again with better docs. Sorry about that inconvenience.

Over all, the current Minidump solution is less then ideal. Unfortunately, I still haven't had the time to start replacing the C++ Breakpad bits with your minidump crate (we also talked about this in https://github.com/getsentry/symbolic/issues/31). I'd be happy to continue the discussion, and with recent insights I think this might be much more feasible than it seamed initially.

**Comment by jan-auer** [comment]
The linked PR should fix this, although I'm not sure if the docs.rs builders actually have enough resources to process something like Breakpad (which is probably stupid to begin with). If not, I will create a feature that replaces all Breakpad functions with empty stubs and activate that for docs.rs builds.
