### ISSUE TITLE
Clarification or example for README bullet

### ISSUE THREAD

**Issue by frostmourne8** [getsentry/symbolic#198]
There is a bullet in the README that drew me to this crate: "Generate Breakpad symbol files from Mach, ELF and PDBs" which would be perfect for something I am trying to accomplish. I am having trouble figuring out how to perform this generation though. Any chance someone could offer clarification and/or update the README with a more detailed explanation?

**Comment by jan-auer** [comment]
We never implemented a full `dump_syms` equivalent, but only the `CFI` part of it. To do that, you'll want to use [`AsciiCfiWriter`](https://docs.rs/symbolic-minidump/7.1.1/symbolic_minidump/cfi/struct.AsciiCfiWriter.html).

To write `FUNC` and `PUBLIC` records, you would roughly have to do the following:
- Open an [`Object`](https://docs.rs/symbolic-debuginfo/7.1.1/symbolic_debuginfo/enum.Object.html) from the input file.
- Get the `debug_session` and generate `FUNC` records for all functions returned by [`functions`](https://docs.rs/symbolic-debuginfo/7.1.1/symbolic_debuginfo/enum.ObjectDebugSession.html#method.functions). Skip inlinees, since Breakpad doesn't support that.
- Iterate through [`symbols`](https://docs.rs/symbolic-debuginfo/7.1.1/symbolic_debuginfo/enum.Object.html#method.symbols) and emit missing ones as `PUBLIC` record.
- You can have a look at [this function](https://github.com/getsentry/symbolic/blob/d217a9340df3bbd373323b732880a95e6de353bf/symcache/src/writer.rs#L209) for an example of how to iterate functions and symbols to emit those in order.

It makes sense to add a `dump_syms` example program to showcase this. I'll leave this issue open for that.

You might also want to have a look at Mozilla's [dump_syms](https://github.com/mozilla/dump_syms) which is a more complete implementation that's partially based on `symbolic`.

**Comment by vaind** [comment]
I'd vote for closing this as out-of-scope, considering [`dump_syms`](https://github.com/mozilla/dump_syms) existence.
