### ISSUE TITLE
[debuginfo] No link under CodeId and DebugId in the docs

### ISSUE THREAD

**Issue by calixteman** [getsentry/symbolic#203]
https://docs.rs/symbolic-debuginfo/7.2.0/symbolic_debuginfo/enum.Object.html#method.code_id
https://docs.rs/symbolic-debuginfo/7.2.0/symbolic_debuginfo/enum.Object.html#method.debug_id

**Comment by jan-auer** [comment]
Interesting, I noticed something similar with the top-level crate where only two of the exports are linked:
https://docs.rs/symbolic/7.2.0/symbolic/

This started with recent versions, only.

**Comment by jan-auer** [comment]
Fixed in 7.3.0, for example:
https://docs.rs/symbolic/7.3.0/symbolic/debuginfo/enum.Object.html#method.debug_id

Note that docs are inlined now into `symbolic`. It still occurs inside `symbolic-debuginfo`, and I don't fully know why. My guess is that it's due to the re-export in `symbolic-common`. In that case, we could also inline the docs for the two types.
