### ISSUE TITLE
RFC: Which parts of symbolic-cabi/python are still relevant?

### ISSUE THREAD

**Issue by loewenheim** [getsentry/symbolic#573]
There are parts of `symbolic-cabi` / python bindings that we ourselves don't use and would be tempted to remove. Before we do that, we'd like to make sure we don't pull the rug out under other people's feet. So what features of symbolic are people actually using through `symbolic-cabi`/python?

cc @gabrielesvelto

**Comment by gabrielesvelto** [comment]
We don't use the Python bindings in the tools we use in Firefox builds however I don't know if we use them inside the server-side crash reporting machinery. My colleague @willkg might know more about that.

**Comment by willkg** [comment]
We (Mozilla) use the Python bindings in the Mozilla Symbolication Service that I wrote last year. Because symbolic was changing and MSS needed to do some wonky things with it, I isolated all the usage to a single shim library:

https://github.com/mozilla-services/tecken/blob/main/eliot-service/eliot/libsymbolic.py

`symbolic.normalize_debug_id`

https://github.com/mozilla-services/tecken/blob/f14114a55ab59455f194ca50abdd99dee6c64271/eliot-service/eliot/libsymbolic.py#L94

`symbolic.Archive.open`

https://github.com/mozilla-services/tecken/blob/f14114a55ab59455f194ca50abdd99dee6c64271/eliot-service/eliot/libsymbolic.py#L127

`archive.get_object`

https://github.com/mozilla-services/tecken/blob/f14114a55ab59455f194ca50abdd99dee6c64271/eliot-service/eliot/libsymbolic.py#L128

`obj.make_symcache`

https://github.com/mozilla-services/tecken/blob/f14114a55ab59455f194ca50abdd99dee6c64271/eliot-service/eliot/libsymbolic.py#L129

`symbolic.SymCache.from_bytes`

https://github.com/mozilla-services/tecken/blob/f14114a55ab59455f194ca50abdd99dee6c64271/eliot-service/eliot/libsymbolic.py#L129

`symcache.dump_into`

https://github.com/mozilla-services/tecken/blob/f14114a55ab59455f194ca50abdd99dee6c64271/eliot-service/eliot/libsymbolic.py#L175

Oh, hrm... there are some things that aren't in the shim:

`SymCache.lookup` and a bunch of `LineInfo` property access:

https://github.com/mozilla-services/tecken/blob/main/eliot-service/eliot/symbolicate_resource.py#L435-L458

It's feasible that we could rewrite MSS in Rust and then we wouldn't need the Python bindings at all, but I'm not sure when I could do that work. It's also possible we could maintain our own Python bindings. I haven't done that before with Rust, but I've done it with other libraries.

I'm pretty sure there are other scripts in Mozilla using the Python bindings to do similar things. Namely, parse sym files, do lookups, and then access `LineInfo` properties.

**Comment by Swatinem** [comment]
Thanks for the feedback, that is good to know. It helps us to know which python bindings we should be carrying around (at least for one more major version).

Something we talked about a couple of times and might also be very relevant to your usecase:
SymCache files themselves were never intended for long-term storage, and for various reasons (mostly bugs and improvements in the writer/converter) it might be a good idea to regenerate those from the original object files.
In the upcoming major / breaking release, we will remove read support for older symcache files.

How much of an inconvenience would that be for you?

**Comment by willkg** [comment]
I knew that symcache format wasn't intended as a long-term stable format, so this is no inconvenience at all!

Eliot (the Mozilla Symbolication Server) caches symcache files on disk in a LRU cache and when we do a deploy, those nodes go away and we promote new nodes which start with an empty disk cache. With the current architecture, we'll never be in a situation where Eliot is trying to read symcache files built by a different version of symbolic than the one installed.

**Comment by loewenheim** [comment]
Symbolic 9.0.0 is now out. Thank you all very much for your input!
