### ISSUE TITLE
symbolic_demangle DemangleOptions support only get parameters?

### ISSUE THREAD

**Issue by anranziruo** [getsentry/symbolic#671]

**Comment by souredoutlook** [comment]
@getsentry/owners-native @zhangchao1 hey all, looks like the Issue could use some additional info.

**Comment by zhangchao1** [comment]
···
let view = ByteView::open("main.dSYM/Contents/Resources/DWARF/main")?;
let objects = Object::parse(&view)?;
 let session = objects.debug_session()?;
for fn_name in session.functions().into_iter(){
       println!("{:?}",fn_item);
}
···
The Function contain debug unit info?
@souredoutlook

**Comment by Swatinem** [comment]
I’m not sure what exactly you mean?
We do prefer the symbol name from the symbol table for top-level functions.
Otherwise we fall back to `DW_AT_linkage_name` and `DW_AT_name`, which we also use for inlined functions.

We also demangle symbols completely by default, with argument types and return types. The exception is the PDB type formatter which I think does not support return types for now.

**Comment by Swatinem** [comment]
We do expose the raw mangled name as well, if there is more specific need for demangling, you can reach for the crates that do that directly.
