### ISSUE TITLE
Use Clippy GitHub action to get annotations

### ISSUE THREAD

**Issue by vaind** [getsentry/symbolic#731]
It would be nice if we could get annotations directly in the PR instead of searching the CI log and/or emails.

https://github.com/marketplace/actions/rust-clippy-check could do that

**Comment by jan-auer** [comment]
We used it in the past, but ended up removing it from symbolic, symbolicator and all other repositories. Does @flub remember what the original reasoning was?

**Comment by jan-auer** [comment]
We could revert to use `actions-rs/cargo` for all cargo invocations like we do in [Relay](https://github.com/getsentry/relay/blob/aeab49ea91dca93fd7412c246a0b3e6e0ddb57b4/.github/workflows/ci.yml#L60-L64). It's an approved action should give us annotation support. 

@Swatinem I can see that this was further changed in https://github.com/getsentry/symbolic/pull/723 without coordinating with Relay or the Rust channel. Can you elaborate on the reasoning, since the PR does not contain much information?

**Comment by flub** [comment]
> We used it in the past, but ended up removing it from symbolic, symbolicator and all other repositories. ~Does @flub remember what the original reasoning was?~
> 
> **Edit:** [getsentry/symbolicator#350](https://github.com/getsentry/symbolicator/pull/350) was the first PR where we changed it. It seems that we tested the annotations and they used to work at the time.

`git log --grep=clippy .github/workflows/ci.yml` but you already found the commit :)

**Comment by Swatinem** [comment]
`actions-rs` is unmaintained: https://github.com/actions-rs/toolchain/issues/216

It spews some deprecation warnings and will likely stop working once those deprecations go into effect (github turning off node 12 support, and `set-output` changes)

Its also just an unnecessary wrapper around `rustup` / `cargo`, and you are better just calling those directly.

I believe I brought this up at some point in some channel, can’t remember anymore.

**Comment by vaind** [comment]
I see that the clippy action I've suggested is from the same unmaintained org. No point in switching in that case.
