### ISSUE TITLE
Symbolic not Works

### ISSUE THREAD

**Issue by l0nax** [getsentry/symbolic#75]
I have setup Sentry on localhost.
Symbolic is "activated" on INSTALLED_APPLICATIONS
but i don't can use the Symbolics:
![bildschirmfoto von 2018-06-17 18-05-06](https://user-images.githubusercontent.com/29659953/41510219-f1bae254-7260-11e8-91da-47dd1ac54748.png)

Do i need [Symbol Server](https://github.com/getsentry/symbolserver) to use Minidump(/ Breakpad) Files

**Comment by jan-auer** [comment]
Hi @l0nax, if you have successfully completed the setup on your local machine then `symbolic` is automatically installed. It is a package used by Sentry internally, and you do not have to activate it or perform any other installation steps. Symbol Server is optional and currently only useful for iOS crashes.

The page you are seeing is because your local Sentry has probably not fetched the latest docs. However, minidumps will still work. See the following resources for working with minidumps on Sentry:

 - Documentation is located at: https://docs.sentry.io/clients/minidump/
 - The minidump endpoint URL can be found in _Project Settings > Client Keys (DSN) > Minidump Endpoint_
 - Note that uploaders sometimes require HTTPS, depending on which client you are using in your application.
 - For integrating with Electron, see https://docs.sentry.io/clients/electron/

I'm closing this issue now, but feel free to reach out if you still have questions.

**Comment by l0nax** [comment]
@Jan-aur There not exists a _Minidump Endpoint_ Under _Project Settings_ > _Client Keys (DSN)_

![bildschirmfoto von 2018-06-18 11-45-44](https://user-images.githubusercontent.com/29659953/41529385-4f5e4176-72ed-11e8-94e3-34d8456f2813.png)

**Comment by jan-auer** [comment]
You have to run [Sentry 9.0.0-rc1](https://github.com/getsentry/sentry/releases/tag/9.0.0rc1) or the latest `master`. Version 8.22.0 does not include this feature. Note that updating to these versions will require you to run `sentry upgrade`. 

After this, you should see the minidump endpoint URL.
