### ISSUE TITLE
Portable PDB reader row-size broken for MAUI

### ISSUE THREAD

**Issue by vaind** [getsentry/symbolic#759]
When the Portable PDB reader iterates rows in the `CustomDebugInformation` table in the attached `.pdb` (see [MauiApp1.zip](https://github.com/getsentry/symbolic/files/10748072/MauiApp1.zip)), it determines the row size to be **6**, 

<img width="299" alt="image" src="https://user-images.githubusercontent.com/6349682/219174797-a0132544-ca31-4164-9b27-b7f1625a736d.png">

however when the same file is opened in ILSpy (actually, you need to open the .dll but it loads the .pdb), the row size, according to their offsets, is **8** (see the diff between offsets).

<img width="703" alt="image" src="https://user-images.githubusercontent.com/6349682/219174983-a11ceabf-90cf-486a-99d7-a8161c826478.png">

This causes all the rows except for the first one to be read incorrectly `CustomDebugInformationIterator::next()`, thus not reading the embedded sources even though they're available.

I'm not yet sure what the issue is, any ideas @loewenheim ?

Fixing this should also revert https://github.com/getsentry/symbolic/pull/751

**Comment by loewenheim** [comment]
I'll have a look and see if I can find anything.

**Comment by loewenheim** [comment]
I'm pretty sure I've found the cause. The problem is that the parsing logic incorrectly assumes that the `#Pdb` stream is always paresd before the `#~` stream, which is not necessarily the case. The order is relevant because the `#Pdb` stream contains the sizes of tables referenced by, but not contained in, the ppdb file, and without this information tables can't be parsed correctly.

**Comment by vaind** [comment]
Thanks for the quick fix @loewenheim
